apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
  labels:
    app: ping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: ping:30
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ping
  labels:
    app: ping
spec:
  ports:
  - name: ping
    port: 80
    targetPort: 8080
    nodePort: 32000
  clusterIP: None
  selector:
    app: ping
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
   name: ping-ingress
   annotations:
     ping.ingress.kubernetes.io/rewrite-target: /$1
spec:
   rules:
   - host: hello-world.info
     http:
       paths:
       - path: /ping
         backend:
           serviceName: ping
           servicePort: 80